return {
  large_file_size = 1024 * 1024,  -- 1MiB
  large_file_line = 2000,

  excluded_filetypes = {  -- NOTE: Please keep the `""` as the first element.
    "", "help", "netrw", "tutor", "man", "qf", "query", "log",
    "alpha",
    "aerial", "aerial-nav",
    "cmp_menu", "blink-cmp-menu", "blink-cmp-documentation", "blink-cmp-signature", "blink-cmp-dot-repeat",
    "crunner",
    "chatgpt-input",
    "diff", "DiffviewFiles", "DiffviewFileHistory",
    "DressingInput", "DressingSelect",
    "flash_prompt",
    "glowpreview",
    "hydra_hint",
    "lspinfo", "mason",
    "notify", "noice",
    "NvimTree", "NvimTreeFilter",
    "snacks_input", "snacks_picker_input", "snacks_picker_list", "snacks_picker_preview",
    "snacks_notif", "snacks_notif_history", "snacks_layout_box",
    "snacks_win", "snacks_win_help", "snacks_win_backdrop",
    "snacks_dashboard", "snacks_terminal",
    "bigfile", "image",
    "terminal", "toggleterm",
    "trouble",
    "TelescopePrompt", "TelescopeResults",
    "packer", "lazy", "lazy_backdrop", "yazi",
  },
  excluded_buftypes = { "nofile", "help", "terminal", "prompt", "quickfix" },

  special_files     = { "Cargo.toml", "Makefile", "README.md", "readme.md", "pyproject.toml", ".gitignore", ".gitmodules" },
  ignored_files     = { "^.git$", "^.vscode$", "^.idea$", "^__pycache__$", "^.mypy_cache$", "^.DS_Store$", "^.*.iosinterface$" },
  ignored_patterns   = {
    "^.git/",
    "^.vscode/",
    "^.idea/",

    "^node_modules/",
    "^__pycache__/",

    "^.local/",
    "^.cache/",
    "^.Trash/",
    "^.terminfo/",

    "^Applications/",
    "^Desktop/",
    "^Documents/",
    "^Downloads/",
    "^Library/",
    "^Movies/",
    "^Music/",
    "^Pictures/",
  },
}
