-- TODO: Fully generated by Claude Code, not yet manually reviewed.

-- Resolve the Claude config root portably.
local function claude_root()
  local env = vim.env.CLAUDE_CONFIG_DIR
  if env and env ~= "" then return env end
  for _, c in ipairs({ vim.fn.expand("~/.claude"), vim.fn.expand("~/.config/claude") }) do
    if vim.fn.isdirectory(c .. "/projects") == 1 then return c end
  end
  return vim.fn.expand("~/.claude")
end

local function clean(s)
  s = (s or ""):gsub("%s+", " "):gsub("^%s+", "")
  if vim.fn.strchars(s) > 60 then s = vim.fn.strcharpart(s, 0, 57) .. "..." end
  return s
end

-- Parse a transcript for a readable title and its project cwd. Cached by
-- mtime so unchanged sessions are not re-read.
local meta_cache = {}
local function session_meta(path)
  local mtime = vim.fn.getftime(path)
  local c = meta_cache[path]
  if c and c.mtime == mtime then return c end

  local ai, summary, last_prompt, first_user, cwd
  local ok, lines = pcall(vim.fn.readfile, path)
  if ok then
    for _, line in ipairs(lines) do
      local ok2, e = pcall(vim.json.decode, line)
      if ok2 and type(e) == "table" then
        if not cwd and type(e.cwd) == "string" then cwd = e.cwd end
        local ty = e.type
        if ty == "ai-title" and type(e.aiTitle) == "string" then
          ai = e.aiTitle                       -- keep the latest title
        elseif ty == "summary" and type(e.summary) == "string" then
          summary = e.summary
        elseif ty == "last-prompt" and type(e.lastPrompt) == "string" then
          last_prompt = e.lastPrompt
        elseif not first_user and ty == "user" and not e.isMeta
          and type(e.message) == "table" and e.message.role == "user" then
          local content, text = e.message.content, nil
          if type(content) == "string" then
            text = content
          elseif type(content) == "table" then
            for _, b in ipairs(content) do
              if type(b) == "table" and b.type == "text" then text = b.text; break end
            end
          end
          -- skip command/meta wrappers like <local-command-stdout>
          if text and not text:match("^%s*<") then first_user = text end
        end
      end
    end
  end

  local m = {
    mtime = mtime,
    title = ai or summary or last_prompt or first_user,
    cwd = cwd,
  }
  meta_cache[path] = m
  return m
end

-- Render a transcript as a readable markdown conversation for the preview.
-- Cached by mtime so scrolling the list does not re-parse the same file.
local convo_cache = {}
local function render_conversation(path)
  local mtime = vim.fn.getftime(path)
  local c = convo_cache[path]
  if c and c.mtime == mtime then return c.lines end

  local out = {}
  local function add(s)
    for _, l in ipairs(vim.split(s, "\n", { plain = true })) do out[#out + 1] = l end
  end

  local ok, lines = pcall(vim.fn.readfile, path)
  if ok then
    for _, line in ipairs(lines) do
      local ok2, e = pcall(vim.json.decode, line)
      local msg = ok2 and type(e) == "table" and e.message
      -- main-thread user/assistant turns only (skip subagents + meta)
      if msg and type(msg) == "table" and not e.isSidechain and not e.isMeta
        and (e.type == "user" or e.type == "assistant") then
        local texts, tools = {}, {}
        local content = msg.content
        if type(content) == "string" then
          texts[#texts + 1] = content
        elseif type(content) == "table" then
          for _, b in ipairs(content) do
            if type(b) == "table" then
              if b.type == "text" and type(b.text) == "string" and b.text ~= "" then
                texts[#texts + 1] = b.text
              elseif b.type == "tool_use" and b.name then
                tools[#tools + 1] = b.name
              end
              -- tool_result / thinking / image blocks are skipped
            end
          end
        end

        -- drop slash-command wrappers and empty turns
        local body = {}
        for _, t in ipairs(texts) do
          if not t:match("^%s*<command") and not t:match("^%s*<local%-command") then
            body[#body + 1] = t
          end
        end

        if #body > 0 or #tools > 0 then
          add(msg.role == "user" and "## 👤 User" or "## 🤖 Claude")
          add("")
          for _, t in ipairs(body) do add(t); add("") end
          for _, name in ipairs(tools) do add("`🔧 " .. name .. "`") end
          if #tools > 0 then add("") end
          add("---")
          add("")
        end
      end
    end
  end
  if #out == 0 then out = { "*(no conversation content)*" } end

  convo_cache[path] = { mtime = mtime, lines = out }
  return out
end

-- opts.all = start in "all projects" mode instead of the current project.
local function claude_sessions(opts)
  local slug = vim.fn.getcwd():gsub("[/.]", "-")
  local show_all = opts and opts.all or false

  Snacks.picker.pick({
    title = "Claude sessions  (<C-d> delete  <C-a> scope)",
    finder = function()
      local pattern = show_all
      and "/projects/*/*.jsonl"             -- every project
      or  ("/projects/" .. slug .. "/*.jsonl") -- just this project
      local items = {}
      for _, path in ipairs(vim.fn.glob(claude_root() .. pattern, false, true)) do
        local t = vim.fn.getftime(path)
        local m = session_meta(path)
        local title = m.title or vim.fn.fnamemodify(path, ":t:r")
        -- project label from the recorded cwd, falling back to the dir slug
        local proj = m.cwd and vim.fn.fnamemodify(m.cwd, ":t")
        or vim.fn.fnamemodify(path, ":h:t")
        items[#items + 1] = {
          file = path,
          title = clean(title),
          proj = proj,
          when = os.date("%Y-%m-%d %H:%M", t),
          sort = t,
          text = (m.title or "") .. " " .. proj .. " " .. path, -- matchable
        }
      end
      table.sort(items, function(a, b) return a.sort > b.sort end)
      return items
    end,
    format = function(item)
      local out = {}
      if show_all then out[#out + 1] = { "[" .. item.proj .. "] ", "SnacksPickerDir" } end
      out[#out + 1] = { item.title, "SnacksPickerLabel" }
      out[#out + 1] = { "  " .. item.when, "SnacksPickerComment" }
      return out
    end,
    preview = function(ctx)
      local item = ctx.item
      if not item then return end
      ctx.preview:reset()
      ctx.preview:set_title(item.title)
      ctx.preview:set_lines(render_conversation(item.file))
      ctx.preview:highlight({ ft = "markdown" })
    end,
    confirm = function(picker, item)
      picker:close()
      if item then vim.cmd("edit " .. vim.fn.fnameescape(item.file)) end
    end,
    actions = {
      delete_session = function(picker, item)
        if not item then return end
        if vim.fn.confirm("Delete '" .. item.title .. "'?", "&Yes\n&No", 2) == 1 then
          vim.fn.delete(item.file)
          meta_cache[item.file] = nil
          convo_cache[item.file] = nil
          picker:find()
        end
      end,
      toggle_scope = function(picker)
        show_all = not show_all
        picker:find() -- re-run the finder with the new scope
      end,
    },
    win = {
      input = {
        keys = {
          ["<c-d>"] = { "delete_session", mode = { "n", "i" } },
          ["dd"] = { "delete_session", mode = "n" },
          ["<c-a>"] = { "toggle_scope", mode = { "n", "i" } },
        },
      },
    },
  })
end

-- :ClaudeSessions      -> current project
-- :ClaudeSessions all  -> all projects
vim.api.nvim_create_user_command("ClaudeSessions", function(o)
  claude_sessions({ all = o.args == "all" })
end, { nargs = "?", complete = function() return { "all" } end })
